apiVersion: apps/v1
kind: Deployment
metadata:
  name: comm-server-2-deployment
  namespace: apps
  labels:
    app: comm-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comm-server-2
  template:
    metadata:
      labels:
        app: comm-server-2
      annotations:
        # Enable Istio sidecar injection
        sidecar.istio.io/inject: "true"
    spec:
      imagePullSecrets:
      - name: app-service-tls # Use your image pull secret name
      containers:
      - name: comm-server-2
        image: docker-registry.docker-registry.svc.cluster.local:5000/comm-server-2:IMAGE_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: PORT
          value: "8002" # Set the PORT environment variable
